version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '8'  # Limit to 10 CPU cores to simulate consumer grade CPU
          memory: '16G'  # Typical consumer grade RAM
    environment:
      - MKL_NUM_THREADS=8
      - OMP_NUM_THREADS=8
      - OPENBLAS_NUM_THREADS=8
      - VECLIB_MAXIMUM_THREADS=8
      - NUMEXPR_NUM_THREADS=8
      - TOKENIZERS_PARALLELISM=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 